employee_name=input('Enter Employee name:')
employee_id=input('Enter Employee id:')
basic_monthly_salary=float(input('Enter basic monthly salary:'))
special_allowances=float(input('Enter Employee allowances:'))
bonus_percentage=float(input('Enter Employee bonus:'))
gross_monthly_salary=basic_monthly_salary + special_allowances
gross_annual_salary=(gross_monthly_salary*12) + (bonus_percentage/100 * (gross_monthly_salary*12))
print('-'*50)
print('Employee details:')
print('-'*50)
print(f'%-20s :{employee_name}'%('Employee name'))
print(f'%-20s :{employee_id}'%('Employee id'))
print(f'%-20s :{gross_monthly_salary}'%('Gross monthly salary'))
print(f'%-20s :{gross_annual_salary}'%('Gross annual salary'))
